# Generated by Django 6.0.4 on 2026-04-17 07:42

from django.db import migrations, models
import django.contrib.auth.hashers


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
    ]
