# Generated by Django 6.0.4 on 2026-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='!', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
