# Generated by Django 6.0.4 on 2026-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_user_password_hash_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
