# Generated by Django 6.0.4 on 2026-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_user_password_user_password_hash'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='user',
                    name='password_hash',
                ),
                migrations.AddField(
                    model_name='user',
                    name='password',
                    field=models.CharField(
                        db_column='password_hash',
                        max_length=255,
                        verbose_name='password',
                    ),
                ),
            ],
        ),
    ]
