# Generated by Django 6.0.4 on 2026-04-20 10:06

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_use_abstract_base_user_password_field'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.tenants.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=255),
        ),
    ]
