# Generated by Django 6.0.4 on 2026-04-13 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('osv', 'OSV'), ('nvd', 'NVD'), ('github', 'GitHub Advisory')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=10)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('affected_ranges', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vulnerabilities_vulnerability',
                'indexes': [models.Index(fields=['severity', 'published_at'], name='vulnerabili_severit_09b7e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.IntegerField()),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assets.asset')),
            ],
            options={
                'db_table': 'vulnerabilities_risksnapshot',
                'indexes': [models.Index(fields=['asset', 'recorded_at'], name='vulnerabili_asset_i_57eb26_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted', 'Accepted Risk'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='assets.asset')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='assets.package')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='vulnerabilities.vulnerability')),
            ],
            options={
                'db_table': 'vulnerabilities_finding',
                'indexes': [models.Index(fields=['asset', 'status', 'risk_score'], name='vulnerabili_asset_i_c68333_idx')],
                'unique_together': {('asset', 'vulnerability', 'package')},
            },
        ),
    ]
