# Generated by Django 6.0.4 on 2026-04-13 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('server', 'Server'), ('container', 'Container'), ('database', 'Database'), ('endpoint', 'Endpoint')], max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], default='production', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.organization')),
            ],
            options={
                'db_table': 'assets_asset',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('ecosystem', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='assets.asset')),
            ],
            options={
                'db_table': 'assets_package',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'risk_score'], name='idx_asset_org_risk'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['name', 'ecosystem'], name='idx_package_name_eco'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('asset', 'name', 'version', 'ecosystem')},
        ),
    ]
